import type { Config } from 'jest'
import nextJest from 'next/jest.js'

const createJestConfig = nextJest({ dir: './' })

// All ESM-only packages that react-markdown and remark-gfm depend on.
// next/jest prepends its own node_modules pattern, so we only need to
// append custom patterns here.  The pattern below overrides the default
// by allowing these packages to pass through SWC/Babel.
const esmPackages = [
  'react-markdown',
  'remark-gfm',
  'remark-parse',
  'remark-rehype',
  'rehype-react',
  'unified',
  'bail',
  'is-plain-obj',
  'trough',
  'vfile',
  'vfile-message',
  'unist-util-stringify-position',
  'mdast-util-from-markdown',
  'mdast-util-to-hast',
  'mdast-util-gfm',
  'mdast-util-gfm-autolink-literal',
  'mdast-util-gfm-footnote',
  'mdast-util-gfm-strikethrough',
  'mdast-util-gfm-table',
  'mdast-util-gfm-task-list-item',
  'mdast-util-to-markdown',
  'mdast-util-phrasing',
  'mdast-util-find-and-replace',
  'mdast-util-to-string',
  'micromark',
  'micromark-core-commonmark',
  'micromark-extension-gfm',
  'micromark-extension-gfm-autolink-literal',
  'micromark-extension-gfm-footnote',
  'micromark-extension-gfm-strikethrough',
  'micromark-extension-gfm-table',
  'micromark-extension-gfm-tagfilter',
  'micromark-extension-gfm-task-list-item',
  'micromark-factory-destination',
  'micromark-factory-label',
  'micromark-factory-space',
  'micromark-factory-title',
  'micromark-factory-whitespace',
  'micromark-util-character',
  'micromark-util-chunked',
  'micromark-util-classify-character',
  'micromark-util-combine-extensions',
  'micromark-util-decode-numeric-character-reference',
  'micromark-util-decode-string',
  'micromark-util-encode',
  'micromark-util-html-tag-name',
  'micromark-util-normalize-identifier',
  'micromark-util-resolve-all',
  'micromark-util-sanitize-uri',
  'micromark-util-subtokenize',
  'micromark-util-symbol',
  'micromark-util-types',
  'decode-named-character-reference',
  'character-entities',
  'property-information',
  'hast-util-whitespace',
  'hast-util-to-jsx-runtime',
  'space-separated-tokens',
  'comma-separated-tokens',
  'unist-util-is',
  'unist-util-visit',
  'unist-util-visit-parents',
  'unist-util-position',
  'ccount',
  'devlop',
  'trim-lines',
  'longest-streak',
  'zwitch',
  'html-url-attributes',
  'stringify-entities',
  'character-entities-html4',
  'character-entities-legacy',
  'estree-util-is-identifier-name',
  'markdown-table',
  'parse-entities',
  'character-reference-invalid',
  'is-alphabetical',
  'is-alphanumerical',
  'is-decimal',
  'is-hexadecimal',
  'escape-string-regexp',
]

const config: Config = {
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transformIgnorePatterns: [
    `/node_modules/(?!(${esmPackages.join('|')})/)`,
  ],
}

export default createJestConfig(config)
